config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :pledges
    resources :rewards, only: [:new, :create, :show, :destroy]
  end

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: 'login'
  post 'logout' => 'user_sessions#destroy', as: 'logout'
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :create, Project
        can :create, Reward
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	# validate :amount_not_nil
	validates :amount, presence: true
	belongs_to :backer, class_name: 'User'
	belongs_to :reward
	# belongs_to :project, through: :reward

	def project
		self.reward.project
	end

	# def amount_not_nil
	# 	if self.amount.nil?
	# 		errors.add :amount, "Cannot be empty"
	# 	end
	# end


end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :owner, class_name: 'User'
	has_many :backers, through: :pledges, class_name: 'User'
	has_many :rewards
	has_many :pledges, through: :rewards
	
	accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true
	
	def amount_raised
		self.pledges.sum(:amount)
	end

	def match_reward(amount)
		rewards.where(['amount <= ?', amount]).order('amount desc').first
	end

	def days_left
		"#{((self.end_date.getlocal - Time.now.getlocal)/86400).truncate} D, #{(((self.end_date.getlocal - Time.now.getlocal)/86400).modulo(1)*24).round} H"
	end

	def backed_by_user?(current_user)
		backers.include?(current_user)
	end

	def select_reward_tier(reward_amount)
		rewards.where('amount <= ?', reward_amount).order('amount asc').last
	end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	has_many :pledges
	#belongs_to :backer, through: :pledges, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  
  has_many :pledges, foreign_key: :backer_id
  has_many :rewards, through: :pledges
  has_many :backed_projects, through: :pledges, source: :project
  has_many :owned_projects, class_name: "Project"
  def amount_spent
  	self.pledges.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  	rescue_from CanCan::AccessDenied do |exception|
  		redirect_to root_url, alert: exception.message
  	end

	private
	def not_authenticated
  		redirect_to login_path, alert: "Please login first"
	end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	before_filter :load_project

	def new
		@pledge = Pledge.new(amount: params[:amount])
		@reward = @project.match_reward(@pledge.amount)
	end

	def create
		@reward = @project.select_reward_tier(pledge_params[:amount])
		@pledge = @project.pledges.build(pledge_params)
		@pledge.reward_id = @reward ? @reward.id : nil
		@pledge.backer_id = current_user.id
		@pledge.save		
		# if @pledge.save
		# 	respond_to do |format|
		# 		format.html {redirect_to projects_path, notice: 'Pledge Succesful!'}
		# 		format.js
		# 	end
		# else
		# 	respond_to do |format|
		# 		format.html {render :new}
		# 		format.js
		# 	end			
			
		# end
	end
	def show
		@pledge = Pledge.find(params[:id])
	end

	def load_project
		@project = Project.find(params[:project_id])	
	end


private
	def pledge_params
		params.require(:pledge).permit(:amount)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_login, except: :index 
	load_and_authorize_resource
	
	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		
		if @project.save

			redirect_to projects_url
			
		else
			render :new
		end
			
	end

	def show
		@project = Project.find(params[:id])
		@pledge = Pledge.new(amount: params[:amount])
		@reward = @project.match_reward(@pledge.amount)
	end

	private

	def project_params
		params.require(:project).permit(:name, :goal, :description, :end_date, rewards_attributes: [:id, :amount, :description, :_destroy])
		
	end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
def show
	@reward = Reward.find(params[:id])
end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
  	if @user = login(params[:email], params[:password], params[:remember_me])
 		redirect_back_or_to(root_url notice: 'Login successful')
 	else
 		flash.now[:alert] = 'Login failed'
 		render 'new'
 	end
  end

  def destroy
  	logout
  	redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			auto_login(@user)
			redirect_to projects_url
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end
	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div id="nav">
    <% if current_user %>
      <%= link_to "Logout", :logout, method: :post %>
      <%= link_to "Profile", user_path(current_user.id) %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

<%= yield %>

</body>
</html>

app/views/pledges/_new.html.erb
<h3>Make A Pledge</h3>

<%= form_for [@project, @pledge], remote: true do |f| %>

<div class="main-form">
	<div>
		<%= f.label :amount %> 
		<%= f.number_field :amount, :step => 10, :min => 10 %>
	</div>

	<div class="submit-button"><%= f.submit %></div>
	<div class="errors"></div>
</div>	
<% end %>

app/views/pledges/create.js.erb
<% if @pledge.errors.any? %>
	$(".errors").text('Donation cannot be empty');
<% else %>
	$("#pledge-form").text('Pledge successful!');
	$("#backers").text('Backers: '+ <%= @project.pledges.length %>);
	$("#amount-raised").text('The amount raised: $'+<%= @project.amount_raised %>);
<% end %>

app/views/pledges/new.html.erb
<h1>Make A Pledge</h1>

<%= form_for [@project, @pledge] do |f| %>

<div class="main-form">
	<div>
		<%= f.label :amount %> 
		<%= f.number_field :amount, :step => 10 %>
	</div>
</div>	

<%= f.submit %>
<% end %>

<%= link_to "Back to project", projects_path %>

app/views/projects/_project.html.erb
  <%= link_to project_path(project.id) do %>
  	<h2> 
  	<%= project.name %> 
  	<%= truncate(project.description, length: 100) %>
  	</h2>
  <%end%>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
	<div class="fields">
		<%= f.label :amount %>
		<%= f.number_field :amount, :step => 10 %>
	</div>

	<div class="fields">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<%= link_to_remove_association "remove reward", f %>	
</div>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<div id="projects">
  <%= render @projects %>
</div>

<% if can?(:create, Project) %>
	<%=link_to "Add A New Project", new_project_url %>
<% end %>

app/views/projects/new.html.erb
<h1>Add A New Project</h1>

<br>

<%= form_for @project do |f| %>

<div class="main-form">
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>

	<div>
		<%= f.label :goal %>
		<%= f.number_field :goal, :min => 10, :step => 10 %>
	</div>

	<div>
		<%= f.label :end_date %>
		<%= f.date_field :end_date %>
	</div>

</div>	

<div id="rewards">
	<p>Rewards</p>
	
	<%= f.fields_for :rewards do |reward_fields| %>

	<%= render 'reward_fields', f: reward_fields %>
	<%end%>

	<div class="links">
		<%= link_to_add_association 'add reward', f, :rewards %>
	</div>
</div>
<%= f.submit %>

<%end%>

<br>
<br>

<%= link_to "Back to Projects", projects_url %>

app/views/projects/show.html.erb
<h1><%= @project.name %> </h1>
<h2 id="backers">Backers:<%= @project.pledges.length %> </h2>

<h4> <% if @project.backers.include?(current_user) %> 
		<div class="pledgedtrue">You have pledged this project already!</div>
	<% end %>
		</h4>

	<br>
	<p> Description: <%= @project.description %></p>
	<p> The goal: $<%= @project.goal %> </p>
	<p id="amount-raised"> The amount raised: $<%= @project.amount_raised %> </p>
	<p> Backing Deadline: <%= @project.end_date.strftime('%B %e, %Y') %> </p>
	<p> Days left: <%= @project.days_left%> </p>

	<h3>Rewards</h3>

	<% @project.rewards.each do |reward|%>
		<%= link_to new_project_pledge_path(@project, amount: reward.amount), class: "reward" do %>
			<h2> 
				<%= reward.amount %> 
				<%= reward.description %>
			</h2>
		<% end %>
	<% end %>

	<div id='pledge-form' hidden >
		<%= render 'pledges/new' %>
	</div>

	<%= link_to "Back To Main Page", projects_url %>

app/views/rewards/show.html.erb
<h1> <%= @reward.amount %> </h1>
<p> <%= @reward.description %> </p>
<%= link_to "Back to project", project_path %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :remember_me %><br />
    <%= check_box_tag :remember_me %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<div class 'field'>
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>
	<div class 'field'>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>
	<div class 'field'>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class 'field'>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class 'field'>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class 'field'>
		<%= f.submit %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1>Hello! <%= @user.first_name %> Welcome to your profile!</h1>

<ul>
	<% @user.pledges.each do |pledge| %>
	<li>
	The amount you pledged to: <%= link_to pledge.project.name, project_path(pledge.project.id) %> is $<%= pledge.amount %>
	</li>
	<% end %>
</ul>

<p>Total contributed: $<%= @user.amount_spent %></p>